Promote to version 3.2
flask-api/flask-api pull request #166
Opened 2023-12-06 20:18 UTC by dsakagi

Hi there, it's me again.

I see that there are already commits on the `develop` branch to support Flask 3.0+ but there has not been a release
published to PyPI. From what I saw last time, updating the version string  and the release notes seemed to be 
part of the process, so this PR is the beginning of a request to get this new version out and published so that
users (selfishly: my work) can move forward on Flask versions.

Thanks!

2024-01-10 19:32 UTC, dsakagi commented
@auvipy are you still the maintainer here? I was hoping to get a new version available to support Flask 3.0+

2024-01-10 20:00 UTC, auvipy commented
Yes still maintainer

2024-01-18 15:55 UTC, dsakagi commented
@auvipy great to hear! Do you have available bandwidth to see if this change I proposed is what is necessary to release a new version?

2024-01-18 17:26 UTC, auvipy approved these changes

2024-01-18 17:28 UTC, auvipy requested changes
do we already support flask 3?

2024-01-18 18:34 UTC, dsakagi commented
I had originally intended to make a PR to bring this package up to compatibility with Flask3, but found that on the HEAD commit it had no problems (this was some weeks ago, however, so I'm drawing from memory here).

I believe that this change was the one that brought in the compatiblity: https://github.com/flask-api/flask-api/commit/9c998897f67d8aa959dc3005d7d22f36568b6938

And this one is where Flask3 was added to the testing matrix: https://github.com/flask-api/flask-api/commit/b55221a1d31d9ef73085104b29966c528850abcc

Although I must be honest, I haven't actually found where the test runs can be viewed, so I'm not sure they're green.

2024-02-20 14:04 UTC, auvipy approved these changes

2024-02-20 14:04 UTC, merged

2024-05-22 18:00 UTC, tonynelson19 commented
Are there plans to release version 3.2?